%% ARCGen Main Execution File
% 
% Created By:     D.C. Hartlen, M.ASc, EIT
% Date:           13-Jun-2021
% Updated By:     
% Date:           
% Version:        MATLAB R2020b (older versions not guaranteed)
%
% TODO: add description and syntax

%% Initialization
fclose all;
close all;
clear;
clc;

nResample = 100;
smfact = 1;

% Load data
% load('Data/Lessley Parabolas/Lessley_Parabola_Processed.mat')
% invalidCurves = [4];
% validIndices = not([1:length(responseCurves)]==invalidCurves);
% responseCurves = responseCurves(validIndices);

% load('Data/cRDCB FA2 Trac-Sep/cRdcb_FA2_ExpTracSep.mat')
load('Data/cRDCB FA2 Trac-Sep/cRdcb_FA2_TrapezoidTracSep.mat')

% Curve Smoothing
for i=1:length(responseCurves)
    responseCurves(i).data = ...
        [smooth(responseCurves(i).data(:,1),smfact),...
        smooth(responseCurves(i).data(:,2),smfact)]
end

% Run ARCGen using ellipsoids
[charAvgNorm, innerCorrNorm, outerCorrNorm,quadrants] = ARCGen_Rectangle(responseCurves,...
    'Diagnostics', 'on',...
    'nResamplePoints', nResample,...
    'NormalizeCurves', 'on');

figure();
hold on;
for iPlot = 1:length(responseCurves)
    pExp = plot(responseCurves(iPlot).data(:,1),...
        responseCurves(iPlot).data(:,2),...
        'DisplayName','Exp.',...
        'LineWidth',1,'Color',0.7.*[1,1,1]);
end
pAvg = plot(charAvgNorm(:,1),charAvgNorm(:,2),'.-',...
    'DisplayName','Char. Avg. - ARCGen','MarkerSize',16,...
    'LineWidth',2.5,'Color',0.0.*[1,1,1]);
pCorr = plot(innerCorrNorm(:,1),innerCorrNorm(:,2),'.-','MarkerSize',16,...
    'DisplayName','Corridors',...
    'LineWidth',2.0,'Color',[255, 213, 79]./255);
p = plot(outerCorrNorm(:,1),outerCorrNorm(:,2),'.-','MarkerSize',16,...
    'DisplayName','Corridors',...
    'LineWidth',2.0,'Color',[255, 213, 79]./255);
title('Normalization On')

[charAvg, innerCorr, outerCorr,quadrants] = ARCGen_Rectangle(responseCurves,...
    'Diagnostics', 'on',...
    'nResamplePoints', nResample,...
    'NormalizeCurves', 'off');

figure();
hold on;
for iPlot = 1:length(responseCurves)
    pExp = plot(responseCurves(iPlot).data(:,1),...
        responseCurves(iPlot).data(:,2),...
        'DisplayName','Exp.',...
        'LineWidth',1,'Color',0.7.*[1,1,1]);
end
pAvg = plot(charAvg(:,1),charAvg(:,2),'.-',...
    'DisplayName','Char. Avg. - ARCGen','MarkerSize',16,...
    'LineWidth',2.5,'Color',0.0.*[1,1,1]);
pCorr = plot(innerCorr(:,1),innerCorr(:,2),'.-','MarkerSize',16,...
    'DisplayName','Corridors',...
    'LineWidth',2.0,'Color',[255, 213, 79]./255);
p = plot(outerCorr(:,1),outerCorr(:,2),'.-','MarkerSize',16,...
    'DisplayName','Corridors',...
    'LineWidth',2.0,'Color',[255, 213, 79]./255);
title('Normalization Off')

figure();
hold on;
for iPlot = 1:length(responseCurves)
    pExp = plot(responseCurves(iPlot).data(:,1),...
        responseCurves(iPlot).data(:,2),...
        'DisplayName','Exp.',...
        'LineWidth',1,'Color',0.7.*[1,1,1]);
end

pAvgNorm = plot(charAvgNorm(:,1),charAvgNorm(:,2),'.-',...
    'DisplayName','Char. Avg. - Norm On','MarkerSize',16,...
    'LineWidth',2.5,'Color',[255, 213, 79]./255);
pCorrNorm = plot(innerCorrNorm(:,1),innerCorrNorm(:,2),'.-','MarkerSize',16,...
    'DisplayName','Corridors - Norm On',...
    'LineWidth',2.0,'Color',[255, 213, 79]./255);
p = plot(outerCorrNorm(:,1),outerCorrNorm(:,2),'.-','MarkerSize',16,...
    'DisplayName','Corridors - Norm On',...
    'LineWidth',2.0,'Color',[255, 213, 79]./255);

pAvg = plot(charAvg(:,1),charAvg(:,2),'.-',...
    'DisplayName','Char. Avg. - Norm Off','MarkerSize',16,...
    'LineWidth',2.5,'Color',[55,126,184]./255);
pCorr = plot(innerCorr(:,1),innerCorr(:,2),'.-','MarkerSize',16,...
    'DisplayName','Corridors - Norm Off',...
    'LineWidth',2.0,'Color',[55,126,184]./255);
p = plot(outerCorr(:,1),outerCorr(:,2),'.-','MarkerSize',16,...
    'DisplayName','Corridors - Norm Off',...
    'LineWidth',2.0,'Color',[55,126,184]./255);
legend([pAvgNorm,pCorrNorm,pAvg,pCorr],'Location','Best')
title('Normalization Off')
