% Script used for generating manuscript-grade corridors and images for
% ARCGen publication. Only normalized data is used. Accelerations and
% displacements are contained in separate scripts
%
% R1 - Aug 8, 2021

fclose all;
close all;
clear;
clc;

addpath('../')

nResample = 350;
nCorrPts = 250;
smfact = 1;

%% Plot Head X-Acceleration
load('NBDL 15g Frontal/NBDL 15g Frontal - Head XAccel_PointWiseAvg.mat');
nbdlAvg = pointAvg;
nbdlInner = innerCorr;
nbdlOuter = outerCorr;

load('NBDL 15g Frontal/NBDL 15g Frontal - Head XAccel.mat')
manualIndex = [241, 237, 244, 241, 236, 236, 239]; % Intermediate positive peak

[charAvg, innCorr, outCorr, proCurveData] = ...
    arcgen(responseCurves,...
    'Diagnostics', 'off',...
    'nResamplePoints', nResample,...
    'NormalizeCurves', 'on',...
    'handleOutliers', 'off',...
    'CorridorRes', nCorrPts,...
    'EllipseKFact', 1.0,...
    'minCorridorWidth', 0.0,...
    'nWarpCtrlPts', 4,...
    'warpingPenalty', 1e-2);

figure('Name','Head X-Acceleration');
hold on;
for iPlot = 1:length(responseCurves)
    pExp = plot(proCurveData(iPlot).data(:,1),...
        proCurveData(iPlot).data(:,2),...
        'DisplayName','Exp.',...
        'LineWidth',1,'Color',0.7.*[1,1,1]);
end

pAvgNbdl = plot(nbdlAvg(:,1),nbdlAvg(:,2),'-',...
    'DisplayName','Pointwise Avg.','MarkerSize',16,...
    'LineWidth',2.0,'Color',[55,126,184]./255);
pCorrNbdl = plot(nbdlInner(:,1),nbdlInner(:,2),'-','MarkerSize',6,...
    'DisplayName','Pointwise Corridor',...
    'LineWidth',1.0,'Color',[55,126,184]./255);
p = plot(nbdlOuter(:,1),nbdlOuter(:,2),'-','MarkerSize',6,...
    'DisplayName','Pointwise Corridor',...
    'LineWidth',1.0,'Color',[55,126,184]./255);

pAvg = plot(charAvg(:,1),charAvg(:,2),'-',...
    'DisplayName','Char. Avg.','MarkerSize',16,...
    'LineWidth',2.5,'Color',[0,0,0]);
pCorr = plot(innCorr(:,1),innCorr(:,2),'-','MarkerSize',16,...
    'DisplayName','Corridor',...
    'LineWidth',2.0,'Color',[255, 213, 79]./255);
p = plot(outCorr(:,1),outCorr(:,2),'-','MarkerSize',16,...
    'DisplayName','Corridor',...
    'LineWidth',2.0,'Color',[255, 213, 79]./255);

title('Head X Acceleration')
grid on
xlabel('Time (ms)')
ylabel('Accleration (g)')

%% Plot Head Z-Acceleration
load('NBDL 15g Frontal/NBDL 15g Frontal - Head ZAccel_PointWiseAvg.mat');
nbdlAvg = pointAvg;
nbdlInner = innerCorr;
nbdlOuter = outerCorr;

load('NBDL 15g Frontal/NBDL 15g Frontal - Head ZAccel.mat')
% manualIndex = [243, 227, 237, 241, 237, 224, 241]; % zero-crossing
manualIndex = [243, 229, 235, 242, 238, 226, 240]; % symmetry point/inflection


[charAvg, innCorr, outCorr, proCurveData] = ...
    arcgen(responseCurves,...
    'Diagnostics', 'off',...
    'nResamplePoints', nResample,...
    'NormalizeCurves', 'on',...
    'handleOutliers', 'off',...
    'CorridorRes', nCorrPts,...
    'EllipseKFact', 1.0,...
    'minCorridorWidth', 0.0,...
    'nWarpCtrlPts', 4,...
    'warpingPenalty', 1e-2);

figure('Name','Head Z-Acceleration');
hold on;
for iPlot = 1:length(responseCurves)
    pExp = plot(proCurveData(iPlot).data(:,1),...
        proCurveData(iPlot).data(:,2),...
        'DisplayName','Exp.',...
        'LineWidth',1,'Color',0.7.*[1,1,1]);
end

pAvgNbdl = plot(nbdlAvg(:,1),nbdlAvg(:,2),'-',...
    'DisplayName','Pointwise Avg.','MarkerSize',16,...
    'LineWidth',2.0,'Color',[55,126,184]./255);
pCorrNbdl = plot(nbdlInner(:,1),nbdlInner(:,2),'-','MarkerSize',6,...
    'DisplayName','Pointwise Corridor',...
    'LineWidth',1.0,'Color',[55,126,184]./255);
p = plot(nbdlOuter(:,1),nbdlOuter(:,2),'-','MarkerSize',6,...
    'DisplayName','Pointwise Corridor',...
    'LineWidth',1.0,'Color',[55,126,184]./255);

pAvg = plot(charAvg(:,1),charAvg(:,2),'-',...
    'DisplayName','Char. Avg.','MarkerSize',16,...
    'LineWidth',2.5,'Color',[0,0,0]);
pCorr = plot(innCorr(:,1),innCorr(:,2),'-','MarkerSize',16,...
    'DisplayName','Corridor',...
    'LineWidth',2.0,'Color',[255, 213, 79]./255);
p = plot(outCorr(:,1),outCorr(:,2),'-','MarkerSize',16,...
    'DisplayName','Corridor',...
    'LineWidth',2.0,'Color',[255, 213, 79]./255);

title('Head Z Acceleration')
grid on
xlabel('Time (ms)')
ylabel('Accleration (g)')

%% Plot Head Y Angular Acceleration
load('NBDL 15g Frontal/NBDL 15g Frontal - Head YrotAccel_PointWiseAvg.mat');
nbdlAvg = pointAvg;
nbdlInner = innerCorr;
nbdlOuter = outerCorr;

load('NBDL 15g Frontal/NBDL 15g Frontal - Head YrotAccel.mat')

[charAvg, innCorr, outCorr, proCurveData] = ...
    arcgen(responseCurves,...
    'Diagnostics', 'off',...
    'nResamplePoints', nResample,...
    'NormalizeCurves', 'on',...
    'handleOutliers', 'off',...
    'CorridorRes', nCorrPts,...
    'EllipseKFact', 1.0,...
    'minCorridorWidth', 0.0,...
    'nWarpCtrlPts', 4,...
    'warpingPenalty', 1e-2);

figure('Name','Head Y Angular Acceleration');
hold on;
for iPlot = 1:length(responseCurves)
    pExp = plot(proCurveData(iPlot).data(:,1),...
        proCurveData(iPlot).data(:,2),...
        'DisplayName','Exp.',...
        'LineWidth',1,'Color',0.7.*[1,1,1]);
end

pAvgNbdl = plot(nbdlAvg(:,1),nbdlAvg(:,2),'-',...
    'DisplayName','Pointwise Avg.','MarkerSize',16,...
    'LineWidth',2.0,'Color',[55,126,184]./255);
pCorrNbdl = plot(nbdlInner(:,1),nbdlInner(:,2),'-','MarkerSize',6,...
    'DisplayName','Pointwise Corridor',...
    'LineWidth',1.0,'Color',[55,126,184]./255);
p = plot(nbdlOuter(:,1),nbdlOuter(:,2),'-','MarkerSize',6,...
    'DisplayName','Pointwise Corridor',...
    'LineWidth',1.0,'Color',[55,126,184]./255);

pAvg = plot(charAvg(:,1),charAvg(:,2),'-',...
    'DisplayName','Char. Avg.','MarkerSize',16,...
    'LineWidth',2.5,'Color',[0,0,0]);
pCorr = plot(innCorr(:,1),innCorr(:,2),'-','MarkerSize',16,...
    'DisplayName','Corridor',...
    'LineWidth',2.0,'Color',[255, 213, 79]./255);
p = plot(outCorr(:,1),outCorr(:,2),'-','MarkerSize',16,...
    'DisplayName','Corridor',...
    'LineWidth',2.0,'Color',[255, 213, 79]./255);

title('Head Y Angular Acceleration')
grid on
xlabel('Time (ms)')
ylabel('Angular Accleration (deg/s^2)')

%% Plot T1 X Acceleration
load('NBDL 15g Frontal/NBDL 15g Frontal - T1 XAccel_PointWiseAvg.mat');
nbdlAvg = pointAvg;
nbdlInner = innerCorr;
nbdlOuter = outerCorr;

load('NBDL 15g Frontal/NBDL 15g Frontal - T1 XAccel.mat')

[charAvg, innCorr, outCorr, proCurveData] = ...
    arcgen(responseCurves,...
    'Diagnostics', 'off',...
    'nResamplePoints', nResample,...
    'NormalizeCurves', 'on',...
    'handleOutliers', 'off',...
    'CorridorRes', nCorrPts,...
    'EllipseKFact', 1.0,...
    'minCorridorWidth', 0.0,...
    'nWarpCtrlPts', 3,...
    'warpingPenalty', 1e-2);

figure('Name','T1 X-Acceleration');
hold on;
for iPlot = 1:length(responseCurves)
    pExp = plot(proCurveData(iPlot).data(:,1),...
        proCurveData(iPlot).data(:,2),...
        'DisplayName','Exp.',...
        'LineWidth',1,'Color',0.7.*[1,1,1]);
end

pAvgNbdl = plot(nbdlAvg(:,1),nbdlAvg(:,2),'-',...
    'DisplayName','Pointwise Avg.','MarkerSize',16,...
    'LineWidth',2.0,'Color',[55,126,184]./255);
pCorrNbdl = plot(nbdlInner(:,1),nbdlInner(:,2),'-','MarkerSize',6,...
    'DisplayName','Pointwise Corridor',...
    'LineWidth',1.0,'Color',[55,126,184]./255);
p = plot(nbdlOuter(:,1),nbdlOuter(:,2),'-','MarkerSize',6,...
    'DisplayName','Pointwise Corridor',...
    'LineWidth',1.0,'Color',[55,126,184]./255);

pAvg = plot(charAvg(:,1),charAvg(:,2),'-',...
    'DisplayName','Char. Avg.','MarkerSize',16,...
    'LineWidth',2.5,'Color',[0,0,0]);
pCorr = plot(innCorr(:,1),innCorr(:,2),'-','MarkerSize',16,...
    'DisplayName','Corridor',...
    'LineWidth',2.0,'Color',[255, 213, 79]./255);
p = plot(outCorr(:,1),outCorr(:,2),'-','MarkerSize',16,...
    'DisplayName','Corridor',...
    'LineWidth',2.0,'Color',[255, 213, 79]./255);

grid on
xlabel('Time (ms)')
ylabel('Accleration (g)')

%% Plot T1 Z Acceleration
load('NBDL 15g Frontal/NBDL 15g Frontal - T1 ZAccel_PointWiseAvg.mat');
nbdlAvg = pointAvg;
nbdlInner = innerCorr;
nbdlOuter = outerCorr;

load('NBDL 15g Frontal/NBDL 15g Frontal - T1 ZAccel.mat')

[charAvg, innCorr, outCorr, proCurveData] = ...
    arcgen(responseCurves,...
    'Diagnostics', 'off',...
    'nResamplePoints', nResample,...
    'NormalizeCurves', 'on',...
    'handleOutliers', 'off',...
    'CorridorRes', nCorrPts,...
    'EllipseKFact', 1.0,...
    'minCorridorWidth', 0.0,...
    'nWarpCtrlPts', 4,...
    'warpingPenalty', 1e-2);

figure('Name','T1 Z Acceleration');
hold on;
for iPlot = 1:length(responseCurves)
    pExp = plot(proCurveData(iPlot).data(:,1),...
        proCurveData(iPlot).data(:,2),...
        'DisplayName','Exp.',...
        'LineWidth',1,'Color',0.7.*[1,1,1]);
end

pAvgNbdl = plot(nbdlAvg(:,1),nbdlAvg(:,2),'-',...
    'DisplayName','Pointwise Avg.','MarkerSize',16,...
    'LineWidth',2.0,'Color',[55,126,184]./255);
pCorrNbdl = plot(nbdlInner(:,1),nbdlInner(:,2),'-','MarkerSize',6,...
    'DisplayName','Pointwise Corridor',...
    'LineWidth',1.0,'Color',[55,126,184]./255);
p = plot(nbdlOuter(:,1),nbdlOuter(:,2),'-','MarkerSize',6,...
    'DisplayName','Pointwise Corridor',...
    'LineWidth',1.0,'Color',[55,126,184]./255);

pAvg = plot(charAvg(:,1),charAvg(:,2),'-',...
    'DisplayName','Char. Avg.','MarkerSize',16,...
    'LineWidth',2.5,'Color',[0,0,0]);
pCorr = plot(innCorr(:,1),innCorr(:,2),'-','MarkerSize',16,...
    'DisplayName','Corridor',...
    'LineWidth',2.0,'Color',[255, 213, 79]./255);
p = plot(outCorr(:,1),outCorr(:,2),'-','MarkerSize',16,...
    'DisplayName','Corridor',...
    'LineWidth',2.0,'Color',[255, 213, 79]./255);

grid on
xlabel('Time (ms)')
ylabel('Accleration (g)')