fclose all;
close all;
clear;
clc;

nResample = 250;
nCorrPts = 250;
smFact = 1;

addpath('../')

xlimits = [0,0.40];
ylimits = [0,900];

%% Filter reponse curve data
load('Watson 7333 12R RDCB/WatsonRdcb_7333_12Thou.mat')
for iCurve = 1:size(responseCurves,2)
    responseCurves(iCurve).data = [...
        smooth(responseCurves(iCurve).data(:,1),smFact),...
        smooth(responseCurves(iCurve).data(:,2),smFact)];
end

%% Generate Force-Disp corridors without magnitude normalization
[charAvgNoNorm, innCorrNoNorm, outCorrNoNorm,proCurveDataNoNorm] = ...
    arcgen(responseCurves,...
    'Diagnostics', 'off',...
    'nResamplePoints', nResample,...
    'NormalizeSignals', 'off',...
    'handleOutliers', 'off',...
    'CorridorRes',      nCorrPts,....
    'EllipseKFact',     1.0);

figure('Name','Force-Disp - No Normalization');
hold on;
for iPlot = 1:length(responseCurves)
    pExp = plot(responseCurves(iPlot).data(:,1),...
        responseCurves(iPlot).data(:,2),...
        'DisplayName','Exp.',...
        'LineWidth',1,'Color',0.7.*[1,1,1]);
end

pAvg = plot(charAvgNoNorm(:,1),charAvgNoNorm(:,2),'.-',...
    'DisplayName','Char. Avg. - ARCGen','MarkerSize',16,...
    'LineWidth',2.5,'Color',[0,0,0]);
pCorr = plot(innCorrNoNorm(:,1),innCorrNoNorm(:,2),'.-','MarkerSize',16,...
    'DisplayName','Corridors - ARCGen',...
    'LineWidth',2.0,'Color',[255, 213, 79]./255);
p = plot(outCorrNoNorm(:,1),outCorrNoNorm(:,2),'.-','MarkerSize',16,...
    'DisplayName','Outer',...
    'LineWidth',2.0,'Color',[196, 147, 0]./255);

legend([pExp,pAvg,pCorr], 'Location', 'Best')
xlim(xlimits)
ylim(ylimits)
grid on
xlabel('Deflection (mm)')
ylabel('Force (N)')

%% Generate Force-Disp corridors without magnitude normalization
[charAvgNorm, innCorrNorm, outCorrNorm,proCurveDataNorm] = ...
    arcgen(responseCurves,...
    'Diagnostics', 'off',...
    'nResamplePoints', nResample,...
    'NormalizeSignals', 'on',...
    'handleOutliers', 'off',...
    'CorridorRes',      nCorrPts,....
    'EllipseKFact',     1.0,...
    'nWarpCtrlPts', 0,...
    'warpingPenalty', 1e-2);

figure('Name','Force-Disp - Normalization');
hold on;
for iPlot = 1:length(responseCurves)
    pExp = plot(responseCurves(iPlot).data(:,1),...
        responseCurves(iPlot).data(:,2),...
        'DisplayName','Exp.',...
        'LineWidth',1,'Color',0.7.*[1,1,1]);
end

pAvg = plot(charAvgNorm(:,1),charAvgNorm(:,2),'.-',...
    'DisplayName','Char. Avg. - ARCGen','MarkerSize',16,...
    'LineWidth',2.5,'Color',[0,0,0]);
pCorr = plot(innCorrNorm(:,1),innCorrNorm(:,2),'.-','MarkerSize',16,...
    'DisplayName','Corridors - ARCGen',...
    'LineWidth',2.0,'Color',[255, 213, 79]./255);
p = plot(outCorrNorm(:,1),outCorrNorm(:,2),'.-','MarkerSize',16,...
    'DisplayName','Outer',...
    'LineWidth',2.0,'Color',[196, 147, 0]./255);

legend([pExp,pAvg,pCorr], 'Location', 'Best')
xlim(xlimits)
ylim(ylimits)
grid on
xlabel('Deflection (mm)')
ylabel('Force (N)')