% Script used for generating manuscript-grade corridors and images for
% ARCGen publication. Only normalized data is used. Accelerations and
% displacements are contained in separate scripts
%
% R1 - Aug 8, 2021

fclose all;
close all;
clear;
clc;

addpath('../')

nResample = 500;
nCorrPts = 500;
smfact = 1;

%% Plot Head X-Displacement
load('NBDL 15g Frontal/NBDL 15g Frontal - Head XDisp_PointWiseAvg.mat');
nbdlAvg = pointAvg;
nbdlInner = innerCorr;
nbdlOuter = outerCorr;

load('NBDL 15g Frontal/NBDL 15g Frontal - Head XDisp.mat')

[charAvg, innCorr, outCorr, proCurveData] = ...
    arcgen(responseCurves,...
    'Diagnostics', 'off',...
    'nResamplePoints', nResample,...
    'NormalizeSignals', 'on',...
    'handleOutliers', 'off',...
    'CorridorRes', nCorrPts,...
    'EllipseKFact', 1.0,...
    'minCorridorWidth', 0.0,...
    'nWarpCtrlPts', 2,...
    'warpingPenalty', 1e-2);

figure('Name','Head X-Displacement');
hold on;
for iPlot = 1:length(responseCurves)
    pExp = plot(proCurveData(iPlot).data(:,1),...
        proCurveData(iPlot).data(:,2),...
        'DisplayName','Exp.',...
        'LineWidth',1,'Color',0.7.*[1,1,1]);
end

pAvgNbdl = plot(nbdlAvg(:,1),nbdlAvg(:,2),'-',...
    'DisplayName','Pointwise Avg.','MarkerSize',16,...
    'LineWidth',2.0,'Color',[55,126,184]./255);
pCorrNbdl = plot(nbdlInner(:,1),nbdlInner(:,2),'-','MarkerSize',6,...
    'DisplayName','Pointwise Corridor',...
    'LineWidth',1.0,'Color',[55,126,184]./255);
p = plot(nbdlOuter(:,1),nbdlOuter(:,2),'-','MarkerSize',6,...
    'DisplayName','Pointwise Corridor',...
    'LineWidth',1.0,'Color',[55,126,184]./255);

pAvg = plot(charAvg(:,1),charAvg(:,2),'-',...
    'DisplayName','Char. Avg.','MarkerSize',16,...
    'LineWidth',2.5,'Color',[0,0,0]);
pCorr = plot(innCorr(:,1),innCorr(:,2),'-','MarkerSize',16,...
    'DisplayName','Corridor',...
    'LineWidth',2.0,'Color',[255, 213, 79]./255);
p = plot(outCorr(:,1),outCorr(:,2),'-','MarkerSize',16,...
    'DisplayName','Corridor',...
    'LineWidth',2.0,'Color',[255, 213, 79]./255);

title('Head X Displacement')
grid on
xlabel('Time (ms)')
ylabel('Displacement (mm)')

% Plot Head Z-Displacement
load('NBDL 15g Frontal/NBDL 15g Frontal - Head ZDisp_PointWiseAvg.mat');
nbdlAvg = pointAvg;
nbdlInner = innerCorr;
nbdlOuter = outerCorr;

load('NBDL 15g Frontal/NBDL 15g Frontal - Head ZDisp.mat')

[charAvg, innCorr, outCorr, proCurveData] = ...
    arcgen(responseCurves,...
    'Diagnostics', 'off',...
    'nResamplePoints', nResample,...
    'NormalizeSignals', 'on',...
    'handleOutliers', 'off',...
    'CorridorRes', nCorrPts,...
    'EllipseKFact', 1.0,...
    'minCorridorWidth', 0.0,...
    'nWarpCtrlPts', 2,...
    'warpingPenalty', 1e-2);

figure('Name','Head Z-Displacement');
hold on;
for iPlot = 1:length(responseCurves)
    pExp = plot(proCurveData(iPlot).data(:,1),...
        proCurveData(iPlot).data(:,2),...
        'DisplayName','Exp.',...
        'LineWidth',1,'Color',0.7.*[1,1,1]);
end

pAvgNbdl = plot(nbdlAvg(:,1),nbdlAvg(:,2),'-',...
    'DisplayName','Pointwise Avg.','MarkerSize',16,...
    'LineWidth',2.0,'Color',[55,126,184]./255);
pCorrNbdl = plot(nbdlInner(:,1),nbdlInner(:,2),'-','MarkerSize',6,...
    'DisplayName','Pointwise Corridor',...
    'LineWidth',1.0,'Color',[55,126,184]./255);
p = plot(nbdlOuter(:,1),nbdlOuter(:,2),'-','MarkerSize',6,...
    'DisplayName','Pointwise Corridor',...
    'LineWidth',1.0,'Color',[55,126,184]./255);

pAvg = plot(charAvg(:,1),charAvg(:,2),'-',...
    'DisplayName','Char. Avg.','MarkerSize',16,...
    'LineWidth',2.5,'Color',[0,0,0]);
pCorr = plot(innCorr(:,1),innCorr(:,2),'-','MarkerSize',16,...
    'DisplayName','Corridor',...
    'LineWidth',2.0,'Color',[255, 213, 79]./255);
p = plot(outCorr(:,1),outCorr(:,2),'-','MarkerSize',16,...
    'DisplayName','Corridor',...
    'LineWidth',2.0,'Color',[255, 213, 79]./255);

title('Head Z Displacement')
grid on
xlabel('Time (ms)')
ylabel('Displacement (mm)')

%% Plot Head Y Angular Displacement
load('NBDL 15g Frontal/NBDL 15g Frontal - Head YrotDisp_PointWiseAvg.mat');
nbdlAvg = pointAvg;
nbdlInner = innerCorr;
nbdlOuter = outerCorr;

load('NBDL 15g Frontal/NBDL 15g Frontal - Head YrotDisp.mat')

[charAvg, innCorr, outCorr, proCurveData] = ...
    arcgen(responseCurves,...
    'Diagnostics', 'off',...
    'nResamplePoints', nResample,...
    'NormalizeSignals', 'on',...
    'handleOutliers', 'off',...
    'CorridorRes', nCorrPts,...
    'EllipseKFact', 1.0,...
    'minCorridorWidth', 0.0,...
    'nWarpCtrlPts', 2,...
    'warpingPenalty', 1e-2);

figure('Name','Head Y Angular Displacement');
hold on;
for iPlot = 1:length(responseCurves)
    pExp = plot(proCurveData(iPlot).data(:,1),...
        proCurveData(iPlot).data(:,2),...
        'DisplayName','Exp.',...
        'LineWidth',1,'Color',0.7.*[1,1,1]);
end

pAvgNbdl = plot(nbdlAvg(:,1),nbdlAvg(:,2),'-',...
    'DisplayName','Pointwise Avg.','MarkerSize',16,...
    'LineWidth',2.0,'Color',[55,126,184]./255);
pCorrNbdl = plot(nbdlInner(:,1),nbdlInner(:,2),'-','MarkerSize',6,...
    'DisplayName','Pointwise Corridor',...
    'LineWidth',1.0,'Color',[55,126,184]./255);
p = plot(nbdlOuter(:,1),nbdlOuter(:,2),'-','MarkerSize',6,...
    'DisplayName','Pointwise Corridor',...
    'LineWidth',1.0,'Color',[55,126,184]./255);

pAvg = plot(charAvg(:,1),charAvg(:,2),'-',...
    'DisplayName','Char. Avg.','MarkerSize',16,...
    'LineWidth',2.5,'Color',[0,0,0]);
pCorr = plot(innCorr(:,1),innCorr(:,2),'-','MarkerSize',16,...
    'DisplayName','Corridor',...
    'LineWidth',2.0,'Color',[255, 213, 79]./255);
p = plot(outCorr(:,1),outCorr(:,2),'-','MarkerSize',16,...
    'DisplayName','Corridor',...
    'LineWidth',2.0,'Color',[255, 213, 79]./255);

title('Head Y Rotation')
grid on
xlabel('Time (ms)')
ylabel('Angular Displacement (deg)')

%% Plot T1 X Displacement
load('NBDL 15g Frontal/NBDL 15g Frontal - T1 XDisp_PointWiseAvg.mat');
nbdlAvg = pointAvg;
nbdlInner = innerCorr;
nbdlOuter = outerCorr;

load('NBDL 15g Frontal/NBDL 15g Frontal - T1 XDisp.mat')
% responseCurves(3) = [];

[charAvg, innCorr, outCorr, proCurveData] = ...
    arcgen(responseCurves,...
    'Diagnostics', 'off',...
    'nResamplePoints', nResample,...
    'NormalizeSignals', 'on',...
    'handleOutliers', 'off',...
    'CorridorRes', nCorrPts,...
    'EllipseKFact', 1.0,...
    'minCorridorWidth', 0.0,...
    'nWarpCtrlPts', 2,...
    'warpingPenalty', 1e-2);

figure('Name','T1 X-Displacement');
hold on;
for iPlot = 1:length(responseCurves)
    pExp = plot(proCurveData(iPlot).data(:,1),...
        proCurveData(iPlot).data(:,2),...
        'DisplayName','Exp.',...
        'LineWidth',1,'Color',0.7.*[1,1,1]);
end

pAvgNbdl = plot(nbdlAvg(:,1),nbdlAvg(:,2),'-',...
    'DisplayName','Pointwise Avg.','MarkerSize',16,...
    'LineWidth',2.0,'Color',[55,126,184]./255);
pCorrNbdl = plot(nbdlInner(:,1),nbdlInner(:,2),'-','MarkerSize',6,...
    'DisplayName','Pointwise Corridor',...
    'LineWidth',1.0,'Color',[55,126,184]./255);
p = plot(nbdlOuter(:,1),nbdlOuter(:,2),'-','MarkerSize',6,...
    'DisplayName','Pointwise Corridor',...
    'LineWidth',1.0,'Color',[55,126,184]./255);

pAvg = plot(charAvg(:,1),charAvg(:,2),'-',...
    'DisplayName','Char. Avg.','MarkerSize',16,...
    'LineWidth',2.5,'Color',[0,0,0]);
pCorr = plot(innCorr(:,1),innCorr(:,2),'-','MarkerSize',16,...
    'DisplayName','Corridor',...
    'LineWidth',2.0,'Color',[255, 213, 79]./255);
p = plot(outCorr(:,1),outCorr(:,2),'-','MarkerSize',16,...
    'DisplayName','Corridor',...
    'LineWidth',2.0,'Color',[255, 213, 79]./255);

grid on
xlabel('Time (ms)')
ylabel('Displacement (mm)')
 
%% Plot T1 Z Displacement
load('NBDL 15g Frontal/NBDL 15g Frontal - T1 ZDisp_PointWiseAvg.mat');
nbdlAvg = pointAvg;
nbdlInner = innerCorr;
nbdlOuter = outerCorr;

load('NBDL 15g Frontal/NBDL 15g Frontal - T1 ZDisp.mat')
manualIndex = [295, 287, 274, 314, 219, 286, 306];

[charAvg, innCorr, outCorr, proCurveData] = ...
    arcgen(responseCurves,...
    'Diagnostics', 'off',...
    'nResamplePoints', nResample,...
    'NormalizeSignals', 'on',...
    'handleOutliers', 'off',...
    'CorridorRes', nCorrPts,...
    'EllipseKFact', 1.0,...
    'minCorridorWidth', 0.0,...
    'nWarpCtrlPts', 2,...
    'warpingPenalty', 1e-2);

figure('Name','T1 Z Displacement');
hold on;
for iPlot = 1:length(responseCurves)
    pExp = plot(proCurveData(iPlot).data(:,1),...
        proCurveData(iPlot).data(:,2),...
        'DisplayName','Exp.',...
        'LineWidth',1,'Color',0.7.*[1,1,1]);
end

pAvgNbdl = plot(nbdlAvg(:,1),nbdlAvg(:,2),'-',...
    'DisplayName','Pointwise Avg.','MarkerSize',16,...
    'LineWidth',2.0,'Color',[55,126,184]./255);
pCorrNbdl = plot(nbdlInner(:,1),nbdlInner(:,2),'-','MarkerSize',6,...
    'DisplayName','Pointwise Corridor',...
    'LineWidth',1.0,'Color',[55,126,184]./255);
p = plot(nbdlOuter(:,1),nbdlOuter(:,2),'-','MarkerSize',6,...
    'DisplayName','Pointwise Corridor',...
    'LineWidth',1.0,'Color',[55,126,184]./255);

pAvg = plot(charAvg(:,1),charAvg(:,2),'-',...
    'DisplayName','Char. Avg.','MarkerSize',16,...
    'LineWidth',2.5,'Color',[0,0,0]);
pCorr = plot(innCorr(:,1),innCorr(:,2),'-','MarkerSize',16,...
    'DisplayName','Corridor',...
    'LineWidth',2.0,'Color',[255, 213, 79]./255);
p = plot(outCorr(:,1),outCorr(:,2),'-','MarkerSize',16,...
    'DisplayName','Corridor',...
    'LineWidth',2.0,'Color',[255, 213, 79]./255);

grid on
xlabel('Time (ms)')
ylabel('Displacement (mm)')